### ISSUE TITLE
The extension doesn't work with Gnome 3.28.2

### ISSUE THREAD

**Issue by jollymover** [nzeid/rearrange-activities-gnome-3#1]
Hi nzeid!

Thank you for the great plugin!

Unfortunately, it doesn't work with my Gnome 3.28.2 (CentOS 7.2). Is it possible to fix it?

**Comment by nzeid** [comment]
There are two releases: v4 and v7. For Gnome 3.28, v4 should work.

**Comment by jollymover** [comment]
It works like a charm! All I need is just to enable the extension in gnome-tweaks. Can I donate somehow?

**Comment by nzeid** [comment]
Glad to hear! EDIT: Switched from the cumbersome Bountysource to Buy Me a Coffee: [https://www.buymeacoffee.com/nzeid](https://www.buymeacoffee.com/nzeid)

I don't do any of this for money so literally any amount is appreciated. Thank you!
